Bug 536867 - Support maven mojos refreshing whole folder in BuildContext
Some mojos may need to refresh the whole project folder. This case
currently throws an exception:

java.lang.IllegalArgumentException: Path must include project and
resource name: /org.eclipse.acute.netcoredbg.linux.x86_64
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2117)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:202)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.refreshResources(MavenBuilderImpl.java:246)

This patch prevents this exception from happening.

Change-Id: I7326b46d58c33b93a29658e2dd1cae9dab606a0b
Signed-off-by: Mickael Istria <mistria@redhat.com>